services:
  api:
    build: api
    environment:
      - PORT=3000
      - NEXT_PUBLIC_AUTH_URL=https://251183960.propelauthtest.com
  ui:
    build: ui
    environment:
      - NEXT_PUBLIC_AUTH_URL=https://251183960.propelauthtest.com


  nginx:
    image: nginx:latest
    ports:
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - ui